src/Entity/Category.php
<?php

namespace App\Entity;

use App\Repository\CategoryRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: CategoryRepository::class)]
class Category
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 20)]
    #[Assert\NotBlank]
    #[Assert\Length(max: 20)]
    private ?string $name = null;

    #[ORM\ManyToOne(inversedBy: 'categories')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $owner = null;

    #[ORM\Column(length: 7)]
    #[Assert\Length(exactly: 7)]
    private ?string $color = null;

    #[ORM\OneToMany(mappedBy: 'category', targetEntity: Item::class)]
    private Collection $items;

    public function __construct()
    {
        $this->items = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getOwner(): ?User
    {
        return $this->owner;
    }

    public function setOwner(?User $owner): self
    {
        $this->owner = $owner;

        return $this;
    }

    public function getColor(): ?string
    {
        return $this->color;
    }

    public function setColor(string $color): self
    {
        $this->color = $color;
        return $this;
    }

    public function getRed(): ?string
    {
        return hexdec(substr($this->color, 1, 2));
    }

    public function getGreen(): ?string
    {
        return hexdec(substr($this->color, 3, 2));
    }

    public function getBlue(): ?string
    {
        return hexdec(substr($this->color, 5, 2));
    }

    /**
     * @return Collection<int, Item>
     */
    public function getItems(): Collection
    {
        return $this->items;
    }

    public function addItem(Item $item): self
    {
        if (!$this->items->contains($item)) {
            $this->items->add($item);
            $item->setCategory($this);
        }

        return $this;
    }

    public function removeItem(Item $item): self
    {
        if ($this->items->removeElement($item)) {
            // set the owning side to null (unless already changed)
            if ($item->getCategory() === $this) {
                $item->setCategory(null);
            }
        }

        return $this;
    }


}

src/Form/CategoryType.php
<?php

namespace App\Form;

use App\Entity\Category;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ColorType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CategoryType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name', TextType::class, [
                'required' => true,
                'label' => "Category name"
            ])
            ->add('color', ColorType::class, [
                'label' => "Category color"
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Category::class,
        ]);
    }
}

src/Controller/CategoryController.php
<?php

namespace App\Controller;

use App\Entity\Category;
use App\Entity\User;
use App\Form\CategoryType;
use App\Form\SelectCategoryType;
use App\Service\CategoryService;
use App\Service\ItemService;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Entity;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;

class CategoryController extends AbstractController
{
    private CategoryService $categoryService;
    private ItemService $itemService;

    public function __construct(CategoryService $categoryService, ItemService $itemService)
    {
        $this->categoryService = $categoryService;
        $this->itemService = $itemService;
    }

    #[Route('/users/{id}/categories', name: 'app_categories', requirements: ['id' => '\d+'])]
    #[IsGranted('access', 'user')]
    public function list(User $user): Response
    {
        return $this->render('category/list.html.twig', [
            'categories' => $user->getCategories(),
            'itemsCount' => $this->itemService->getUserItemsCount($user->getId())
        ]);
    }

    #[Route('/users/{userId}/categories/create', name: 'app_category_create', requirements: ['userId' => '\d+'], defaults: ['catId' => null])]
    #[Route('/users/{userId}/categories/{catId}/edit', name: 'app_category_edit', requirements: ['userId' => '\d+', 'catId' => '\d+'])]
    #[Entity('user', options: ['id' => 'userId'])]
    #[Entity('category', options: ['id' => 'catId'])]
    #[IsGranted('access', 'user')]
    public function createEdit(User $user, ?Category $category, Request $request): Response
    {
        if($category)
            $this->denyAccessUnlessGranted('access', $category);
        else
            $category = new Category();

        $form = $this->createForm(CategoryType::class, $category);

        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid())
        {
            $user->addCategory($category);
            $this->categoryService->save($category, true);
            $this->addFlash('success', 'Category successfully created!');
            return $this->redirectToRoute('app_categories', ['id' => $user->getId()]);
        }

        return $this->render('category/create_edit.html.twig', [
            'form' => $form->createView(),
            'create' => !$category->getId(),
            'category' => $category
        ], new Response(null, $form->isSubmitted() && !$form->isValid() ? 422 : 200));
    }

    #[Route('/users/{userId}/categories/{catId}/delete', name: 'app_category_delete', requirements: ['userId' => '\d+', 'catId' => '\d+'])]
    #[Entity('user', options: ['id' => 'userId'])]
    #[Entity('category', options: ['id' => 'catId'])]
    #[IsGranted('access', 'user')]
    #[IsGranted('access', 'category')]
    public function delete(User $user, Category $category, Request $request): Response
    {
        $form = $this->createForm(SelectCategoryType::class, null, [
            'allCategories' => array_filter($user->getCategories()->toArray(), fn (Category $elem) => $elem->getId() !== $category->getId())
        ]);

        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()) {
            $moveToCategory = $form->get('category')->getData();
            $this->categoryService->remove($category, $moveToCategory, true);
            $this->addFlash('success', 'Category successfully deleted!');
            return $this->redirectToRoute('app_categories', ['id' => $user->getId()]);
        }

        return $this->render('category/delete.html.twig', [
            'category' => $category,
            'form' => $form
        ], new Response(null, $form->isSubmitted() && !$form->isValid() ? 422 : 200));
    }
}

templates/category/_all_items_category_preview.html.twig
<a
    href="{{ path('app_items', {userId: app.user.id}) }}"
    class="flex items-center gap-4 py-2.5 px-4 rounded-lg border border-slate-100 shadow hover:bg-gray-100 overflow-x-auto">
    <div class="inline-block w-3 h-3 rounded-full bg-secondary"></div>
    <div>
        <h2 class="text-xl">{{ 'All items'|trans }}</h2>
        <p class="text-sm text-gray-600">{{ itemsCount }} {{ 'items'|trans }}</p>
    </div>
</a>

templates/category/_category_preview.html.twig
<div class="relative">
    <div class="flex items-center justify-between py-2.5 px-4 rounded-lg border border-slate-100 shadow hover:bg-gray-100 overflow-x-auto">
        <a class="flex items-center gap-4 basis-full"
           href="{{ path('app_items_category', {userId: app.user.id, catId: category.id}) }}"
        >
            <div
                    class="inline-block w-3 h-3 rounded-full"
                    style="background-color: rgb({{ category.red }}, {{ category.green }}, {{ category.blue }});"
            ></div>
            <div>
                <h2 class="text-xl">{{ category.name }}</h2>
                <p class="text-sm text-gray-600">{{ category.items|length }} {{ 'items'|trans }}</p>
            </div>
        </a>
        <div class="flex gap-8">
            <button
                {{ stimulus_action('kebab-menu', 'toggle', 'click') }}
                class="z-5"
            >
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M12 6.75a.75.75 0 110-1.5.75.75 0 010 1.5zM12 12.75a.75.75 0 110-1.5.75.75 0 010 1.5zM12 18.75a.75.75 0 110-1.5.75.75 0 010 1.5z" />
                </svg>
            </button>
        </div>
    </div>
    <ul class="menu p-2 shadow rounded-box bg-base-100 w-52 absolute bottom-0 right-0 translate-y-full z-10 hidden"
    data-kebab-menu-target="content">
        <li><a href="{{ path('app_category_edit', {userId: app.user.id, catId: category.id}) }}">{{ 'Edit'|trans }}</a></li>
        <li><a href="{{ path('app_category_delete', {userId: app.user.id, catId: category.id}) }}" class="text-error">{{ 'Delete'|trans }}</a></li>
    </ul>
</div>

templates/category/create_edit.html.twig
{% extends 'base.html.twig' %}

{% block metas %}
    <meta name="turbo-cache-control" content="no-preview">
{% endblock %}

{% block title %}
    {% if create %}{{ 'New category'|trans }} {% else %} {{ 'Edit'|trans }} {{ category.name }} {% endif %} | Expiry
{% endblock %}

{% block breadcrumbs %}
    <li><a href="{{ path('app_index') }}">{{ 'Home'|trans }}</a></li>
    <li><a href="{{ path('app_categories', {id: app.user.id}) }}">{{ 'Categories'|trans }}</a></li>
    <li><a href="#">{{ 'New category'|trans }}</a></li>
{% endblock %}

{% block body %}
    <article class="base-article">
        <h1 class="h1">
            {% if create %}{{ 'New category'|trans }} {% else %} {{ 'Edit'|trans }} {{ category.name }} {% endif %}
        </h1>
        {{ form_start(form, {'attr': {'class': 'form-control w-full max-w-md gap-8'}}) }}
        {{ form_row(form.name) }}
        <div class="flex flex-col">
            {{ form_label(form.color) }}
            {{ form_widget(form.color, {'attr': {'class': 'bg-base-100 w-10 h-10'}}) }}
            <div class="text-error font-semibold">
                {{ form_errors(form.color) }}
            </div>
        </div>

        <button type="submit" class="btn btn-primary max-w-md">
            {% if create %} {{ 'Create'|trans }} {% else %} {{ 'save'|trans }} {% endif %}
        </button>

        {{ form_end(form) }}
    </article>
{% endblock %}

templates/category/delete.html.twig
{% extends 'base.html.twig' %}

{% block title %}
{{ 'Delete'|trans }} {{ category.name }} | Expiry
{% endblock %}

{% block breadcrumbs %}
    <li><a href="{{ path('app_index') }}">{{ 'Home'|trans }}</a></li>
    <li><a href="{{ path('app_categories', {id: app.user.id}) }}">{{ 'Categories'|trans }}</a></li>
    <li><a href="#">{{ 'Delete'|trans }} {{ category.name }}</a></li>
{% endblock %}

{% block body %}
    <article class="base-article gap-12">
        <h1 class="h1">{{ 'Delete'|trans }} {{ category.name }}?</h1>
        <div class="alert alert-info shadow-lg max-w-md">
            <div>
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" class="stroke-current flex-shrink-0 w-6 h-6"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path></svg>
                <span>{{ 'You can move all items from %category% to another category'|trans({'%category%': category.name}) }}</span>
            </div>
        </div>
        {{ form_start(form, {'attr': {'class': 'form-control w-full max-w-md gap-8'}}) }}
        {{ form_row(form.category) }}
        <button
            type="submit"
            class="btn btn-error max-w-md col-span-2 block"
            {{ stimulus_controller('sweetalert-confirm', {
                title: 'Delete'|trans ~ ' ' ~ category.name,
                text: 'You won\'t be able to revert this!'|trans,
                confirmButtonText: 'Yes, delete it!'|trans,
                cancelButtonText: 'Cancel'|trans,
            }) }}
        {{ stimulus_action('sweetalert-confirm', 'onSubmit', 'click') }}
        >
        {{ 'Delete'|trans }} {{ category.name }}
        </button>
        {{ form_end(form) }}
    </article>
{% endblock %}

templates/category/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'Categories'|trans }}{% endblock %}

{% block breadcrumbs %}
    <li><a href="{{ path('app_index') }}">{{ 'Home'|trans }}</a></li>
    <li><a href="#">{{ 'Categories'|trans }}</a></li>
{% endblock %}

{% block body %}
        <article class="base-article">
                <h1 class="h1">{{ 'Categories'|trans }}</h1>
                <article class="flex flex-col items-center w-full">
                    {% include 'components/_add_link.html.twig' with {
                        'action': path('app_category_create', {userId: app.user.id}),
                        'text': 'New category'|trans,} %}
                </article>
                <div class="flex flex-col gap-5 mb-12 w-full max-w-xl" {{ stimulus_controller('kebab-menu') }}>
                    {{ include('category/_all_items_category_preview.html.twig') }}
                {% for category in categories %}
                    {{ include('category/_category_preview.html.twig') }}
                {% endfor %}
                </div>
        </article>
{% endblock %}

templates/category/list.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'Categories'|trans }} | Expiry{% endblock %}

{% block breadcrumbs %}
    <li><a href="{{ path('app_index') }}">{{ 'Home'|trans }}</a></li>
    <li><a href="#">{{ 'Categories'|trans }}</a></li>
{% endblock %}

{% block body %}
        <article class="base-article">
                <h1 class="h1">{{ 'Categories'|trans }}</h1>
                <article class="flex flex-col items-center w-full">
                    {% include 'components/_add_link.html.twig' with {
                        'action': path('app_category_create', {userId: app.user.id}),
                        'text': 'New category'|trans,} %}
                </article>
                <div class="flex flex-col gap-5 mb-12 w-full max-w-xl" {{ stimulus_controller('kebab-menu') }}>
                    {{ include('category/_all_items_category_preview.html.twig') }}
                {% for category in categories %}
                    {{ include('category/_category_preview.html.twig') }}
                {% endfor %}
                </div>
        </article>
{% endblock %}